name: Deployment pipeline

on:
  push:
    branches: [testi]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check_skip.outputs.skip }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for skip condition
        id: check_skip
        run: |
          echo "skip=${{
            contains(github.event.head_commit.message, '#skip') ||
            contains(github.event.pull_request.title, '#skip') ||
            contains(github.event.pull_request.body, '#skip')
          }}" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Check style
        run: npm run eslint

      - name: Build application
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Run E2E tests
        run: npm run test:e2e

      # Trigger deployment only if the skip condition is not met (#skip not found)
      - name: Trigger deployment to Render.com
        if: github.event_name == 'push' && needs.simple_deployment_pipeline.outputs.skip != 'true'
        run: curl ${{ secrets.RENDER_DEPLOY_URL }}

  # Tag a new release only if the deployment pipeline succeeded and skip condition is not met
  tag_release:
    needs: [simple_deployment_pipeline]
    if: github.event_name == 'push' && needs.simple_deployment_pipeline.outputs.skip != 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
